version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.4-alpine
    image: python-redis
    ports:
      - "5000:5000"
    networks:
      - appnetwork
  redis:
    image: "redis:alpine"
    volumes:
      - myredisdata:/data
    networks:
      - appnetwork

  redis2:
    image: "redis:alpine"
    volumes:
      - myredisdata2:/data
    networks:
      - appnetwork2
networks:
  appnetwork:
  appnetwork2:

volumes:
  myredisdata:
  myredisdata2:
